services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: framegrab
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: filmgrab
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/framegrab'
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: on-failure

volumes:
  db-data: {}
