services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: framegrab
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d framegrab || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: framegrab
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/framegrab'
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - /c/:/host-c
      - ./output:/usr/src/app/output
    depends_on:
      - db
    restart: on-failure

volumes:
  db-data: {}
